spring:
  datasource:
    url: jdbc:postgresql://xxxxxxxxxx:5432/xxxxxxxxxx?ssl=true&sslfactory=org.postgresql.ssl.NonValidatingFactory
    driverClassName: org.postgresql.Driver
    username: xxxxxxxxxx
    password: xxxxxxxxxx

# http://doma.seasar.org/apidocs/index.html?org/seasar/doma/jdbc/
doma:
  dialect: postgres
  sql-file-repository: no_cache

# プーリング
spring.datasource.tomcat:
    maxActive: 15
    maxIdle: 10
    minIdle: 5
    initialSize: 2
